### ISSUE TITLE
About Path Optimization!

### ISSUE THREAD

**Issue by Lwy-1998** [how4rd/meshflow#5]
It's me again! haha

I have successfully reimplement mesh-flow by c++. Thanks for your help :-)

But I have a new question about computing the smoothed_vertex_displacement here:
[code link](https://github.com/how4rd/meshflow/blob/5607db091a5dedc28e0284e5e9a6dc6d4ac78e4d/meshflowstabilizer.py#L875)
According to the paper, we are computing a smoothed displacement X using Jacobi method, but I don't understand why P(r) is equal to P(t) in the iteration.

In my opinion , the P(r) should be precomputed by a smoothed technique(e.g gaussian filtering , Kalman filtering...).But this does stabilized videos, so I must misunderstand something.

This is the equation in the paper,
![image](https://user-images.githubusercontent.com/57793811/191179544-35516bd7-7439-4239-8896-965c7b0fba75.png)

**Comment by how4rd** [comment]
Congrats on the implementation!

I'm afraid I don't fully understand your question... here are a few things that might help though.

In the screenshot above, the summation over $r$ specifically says that $r \neq t$, but in the piece of code you linked, it allows $r = t$. Either way, you get the same output. That's because $\omega_{t,r} = \exp\left( -\left(r - t \right)^2 / \left( \Omega_t / 3 \right)^2 \right)$, which equals 0 when $r = t$. As a result, the $r = t$ term in the summation is always 0, so it doesn't matter whether or not you include it in the summation.

As for why $P^{(\zeta)}(r)$ is in the equation, that is just because the Jacobi method is iterative. For a given node in the mesh, during the $\zeta$-th iteration, the program computes the node's displacements $P^{(\zeta)} \left( t \right)$ at every frame $t$ in the video, and then it uses those values during the next iteration to compute better displacements $P^{(\zeta + 1)} \left( t \right)$ at every frame $t$ in the video. Repeating this process eventually converges on the ideal displacements at every point in the video, although I don't understand why mathematically it converges. As for your suggestion to precompute some values, maybe you could precompute some initial values of each displacement, then refine them using the Jacobi method (so you would precompute each $P^{\left( 0 \right)} \left( t \right)$ and then the Jacobi method could continue finding each $P^{\left( 1 \right)} \left( t \right), P^{\left( 2 \right)} \left( t \right), \dots$). I don't know what difference, if any, that technique would make compared to the current approach.

Did this help at all? If not, could you elaborate on your question?

**Comment by Lwy-1998** [comment]
Thanks!

Apologies, I am not really good at English , I am trying to explain it as far as I can, hahaha!

![image](https://user-images.githubusercontent.com/57793811/192699343-8ed7b8c8-82f6-4482-921e-86edbf371f66.png)
This is the Optimization equation we derive from the paper.We need to obtain the P(t) using Jacobi iterative method.
The first term encourage the stabilized video staying close to the original path ,so in my intuition ,the second term encourage the path staying close to the stabilized path. My question is  "where is the stabilized path comes from?"

referring to your explanation, can I roughly regard the P^{ζ}_{r} equals to P^{ζ-1}_{t} , after several iterations,the P^{ζ}_{r} will finally converge to the stabilized path.

I am sorry , I don't know how to write mathematic symbol in GitHub..

**Comment by Lwy-1998** [comment]
Thanks!

Apologies, I am not really good at English , I am trying to explain it as far as I can, hahaha!

![image](https://user-images.githubusercontent.com/57793811/192699343-8ed7b8c8-82f6-4482-921e-86edbf371f66.png)
This is the Optimization equation we derive from the paper.We need to obtain the P(t) using Jacobi iterative method.
The first term encourage the stabilized video staying close to the original path ,so in my intuition ,the second term encourage the path staying close to the stabilized path. My question is  "where is the stabilized path comes from?"

referring to your explanation, can I roughly regard the P^{ζ}_{r} equals to P^{ζ-1}_{t} ?

**Comment by how4rd** [comment]
Don't worry! Honestly your English is good. I think I understand your question now--the optimization equation is confusing because it uses misleading notation and contains a typo. The equation confused me at first too.

(To begin, note that MeshFlow optimizes each node independently of the others. Similarly, MeshFlow optimizes each node's $x$- and $y$-displacements independently. So if there are $n$ nodes, then there are $2n$ independent optimization equations. Of course, in reality, the code can combine those independent $2n$ equations into a single matrix equation to solve all of them in a single function call.)

The first thing that confused me was the symbol $\mathbf{P}\left( t \right)$. When I saw that, I thought it meant "the vector $\mathbf{P}$ at time $t$." In other words, I saw $\mathbf{P}\left( t \right)$ and concluded that $\mathbf{P}\left( 0 \right)$, $\mathbf{P}\left( 1 \right)$, etc. are all different vectors. In that case, the second term in the optimization equation would contain multiple vectors, which wouldn't make sense (as you pointed out).

However, $\mathbf{P}\left( 0 \right)$, $\mathbf{P}\left( 1 \right),$ etc. are actually not different vectors. They are different  entries in the same vector. $\mathbf{P} \left( t \right)$ actually represents the $t$-th entry in vector $\mathbf{P}$, meaning $\mathbf{P} \left( t \right)$ is the node's ideal displacement during frame $t$. That is,
$$\mathbf{P} = \left( \mathbf{P}\left(0\right), \mathbf{P}\left(1\right), \dots, \mathbf{P}\left( f-1 \right) \right)$$
contains the ideal displacement of the node at frames $0, 1, \dots, f-1$.

I found that notation confusing, because I would expect entry $t$ in vector $\mathbf{P}$ to be called $P_t$ or $p_t$. Using that more intuitive notation, we would say
$$\mathbf{P} = \left( p_0, p_1, \dots, p_{f-1} \right).$$

Second, I think the left side of the optimization equation has a typo. It says $\mathcal{O} \left( \mathbf{P} \left( t \right)  \right)$, which means we are picking an optimum $\mathbf{P} \left( t \right) = p_t$... but that's incorrect. We are trying to find the optimal displacements at all frames, not an optimum displacement at just one frame. That is, we are optimizing $\mathbf{P}$ instead of $\mathbf{P} \left( t \right) = p_t$, so the left side of the optimization equation should actually say $\mathcal{O} \left( \mathbf{P} \right)$.

If we rewrite the optimization equation using the more familiar notation, and correcting the left side, it becomes

$$\mathcal{O} \left( \mathbf{P} \right) = \sum_t \left( \lvert p_t - c_t \rvert^2 + \lambda_t \sum_{r \in \Omega_t} \omega_{t,r} \lvert p_t - p_r \rvert ^2 \right).$$
Now, the optimization equation clearly states that we are only optimizing one vector: $\mathbf{P} = \left( p_0, p_1, \dots, p_{f-1} \right)$, which contains the node's optimal displacements at each frame. The Jacobi method will produce an optimum $\mathbf{P}$, and we can repeat that process $2n$ times for the $2n$ optimization equations. We also have a known vector $\mathbf{C} = \left( c_0, c_1, \dots, c_{f-1} \right)$ containing the displacements from the source footage, and a matrix containing all the coefficients $\omega_{t, r}$.

Does this help?

Also, you can write math in GitHub using dollar signs, just like in LaTeX! For example, $\mathbf{P} \left( t \right) = p_t$ is written as: `$\mathbf{P} \left( t \right) = p_t$`

**Comment by Lwy-1998** [comment]
Yeah! it helps a lot! Thank you! 

Sorry for late reply.

Due to your extensive explanation,I think  I understand what is Jacobi doing, I think it just like performing a Gaussian filter across multiple frames(10 frames in your implementation ) but for all frames at the same time.

BTW,Have you ever tried convex optimizing on this problem?

**Comment by how4rd** [comment]
Glad that helped! I haven't tried convex optimization--actually I haven't really explored image stabilization beyond MeshFlow and what's in this repo. If you try modifying MeshFlow to use another optimization technique I'd be curious to hear the results!
